name: alzai
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pandas==1.2.4
  - numpy==1.20.3
  - pip=21.0.1
  - python=3.8.8
  - jupyter
  - matplotlib==3.4.1
  - tensorflow==2.5.0
  - pyyaml==5.4.1
  - pytest==6.2.4
  - pip:
    - dvc==2.1.0
    - opencv-python==4.5.0