name: alzai
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pandas
  - numpy
  - pip=21.0.1
  - python=3.8.8
  - jupyter
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pyyaml
  - pip:
    - dvc