name: alzai
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pandas
  - numpy
  - pip=21.0.1
  - python=3.8.8
  - jupyter
  - matplotlib
  - tensorflow
  - pyyaml
  - pip:
    - dvc
    - opencv-python