stages:
  process:
    cmd: python process.py
    deps:
    - data/raw/alzheimer/
    outs:
    - outs/clean.yaml
  train:
    cmd: python train.py
    outs:
    - outs/metrics.json
    - outs/metrics_visualization.png
    - outs/model.h5
  evaluate:
    cmd: python evaluate.py
    deps:
    - outs/model.h5
    outs:
    - evaluation_metrics.json